<?php

declare(strict_types=1);

namespace Mcbeany\BetterMinion\entities\types;

use Mcbeany\BetterMinion\entities\BaseMinion;
use pocketmine\block\Block;
use pocketmine\entity\animation\ArmSwingAnimation;
use pocketmine\item\Item;
use pocketmine\item\VanillaItems;
use pocketmine\network\mcpe\protocol\LevelEventPacket;
use pocketmine\network\mcpe\protocol\types\LevelEvent;
use pocketmine\world\Position;

class MiningMinion extends BaseMinion{

	protected bool $isMining = false;
	protected int $miningTimer = 0;

	public function getWorkingBlocks() : array{
		$blocks = [];
		$x = (int) $this->getPosition()->getX();
		$y = (int) $this->getPosition()->getY();
		$z = (int) $this->getPosition()->getZ();
		for($i = $x - self::WORKING_RADIUS; $i <= $x + self::WORKING_RADIUS; $i++){
			for($j = $z - self::WORKING_RADIUS; $j <= $z + self::WORKING_RADIUS; $z++){
				if(($i !== $x) && ($j !== $z)){
					$blocks[] = $this->getPosition()->getWorld()->getBlockAt($i, $y - 1, $j);
				}
			}
		}
		return $blocks;
	}

	protected function place(Position $position) : void{
		$this->getInventory()->setItemInHand($this->getMinionInfo()->getRealTarget()->asItem());
		$this->broadcastAnimation(new ArmSwingAnimation($this), $this->getViewers());
		$position->getWorld()->setBlock($position, $this->getMinionInfo()->getRealTarget());
	}

	protected function mine(Block $block){
		$this->isMining = true;
		$breakTime = $this->getMinionInfo()->getRealTarget()->getBreakInfo()->getBreakTime($this->getTool());
		$breakSpeed = $breakTime * 20;
		$this->miningTimer = (int) $breakTime;
		if($breakSpeed > 0){
			$breakSpeed = 1 / $breakSpeed;
		}else{
			$breakSpeed = 1;
		}
		$block->getPosition()->getWorld()->broadcastPacketToViewers($block->getPosition(), LevelEventPacket::create(LevelEvent::BLOCK_START_BREAK, (int) (65535 * $breakSpeed), $block->getPosition()));
	}

	protected function onAction() : bool{
		if($this->isContainInvalidBlock()){
			//TODO: Send minion message in his nametag like "This place isnt perfect :("
			return parent::onAction();
		}
		if($this->isContainAir()){
			$pos = $this->getAirBlock()->getPosition();
			$this->place($pos);
			return parent::onAction();
		}
		if($this->getWorkingBlock() == null){
			$area = $this->getWorkingBlocks();
			$block = $area[array_rand($area)];
			$this->setWorkingBlock($block);
			$this->mine($block);
		}
		return parent::onAction();
	}

	protected function doOfflineAction(int $times) : bool{
		//TODO: Offline action (just add stuff to inventory)
		return parent::doOfflineAction($times);
	}

	protected function entityBaseTick(int $tickDiff = 1) : bool{

		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	protected function getTool() : Item{
		return VanillaItems::DIAMOND_PICKAXE();
		//TODO: Custom for mining minion using shovel
	}
}