---
name: BetterMinion
main: Mcbeany\BetterMinion\BetterMinion
version: 1.0.0
api: 3.21.0
authors:
- Mcbeany
- AIPTU
depend:
- EconomyAPI
- SellAll

permissions:
  betterminion.command:
    default: op
    description: Allows users to use better minion command
...
